import OpenAI from "openai";
import {GoogleGenAI} from "@google/genai";
import os from "os";
import fs from "fs";
import {freeModels,geminiChat,hfChat,pollinationsImage,geminiTTS} from "./free-ai.js";
const openai=process.env.OPENAI_API_KEY?new OpenAI({apiKey:process.env.OPENAI_API_KEY}):null;
const compat=process.env.COMPAT_API_KEY&&process.env.COMPAT_BASE_URL?new OpenAI({apiKey:process.env.COMPAT_API_KEY,baseURL:process.env.COMPAT_BASE_URL}):null;
const xai=process.env.XAI_API_KEY?new OpenAI({apiKey:process.env.XAI_API_KEY,baseURL:"https://api.x.ai/v1"}):null;
const heretic=process.env.HERETIC_BASE_URL?new OpenAI({apiKey:process.env.HERETIC_API_KEY||"no-key",baseURL:process.env.HERETIC_BASE_URL.replace(/\/$/,"")+"/v1"}):null;
const claudeKey=process.env.ANTHROPIC_API_KEY||"";
const chatSystem=()=>process.env.ASSISTANT_SYSTEM_PROMPT||"تو دستیار فارسی Fard021 AI هستی. دقیق، صمیمی، مفید و شفاف پاسخ بده.";
const registry=[
{id:"nano-banana",label:"Google · Nano Banana 2",kind:"image",provider:"google",model:"gemini-3.1-flash-image"},
{id:"nano-banana-lite",label:"Google · Nano Banana 2 Lite",kind:"image",provider:"google",model:"gemini-3.1-flash-lite-image"},
{id:"veo-google",label:"Google · Veo 3.1",kind:"video",provider:"google",model:"veo-3.1-generate-preview"},
{id:"grok",label:"xAI · Grok 4.7",kind:"chat",provider:"xai",model:process.env.XAI_CHAT_MODEL||"grok-4.7"},
{id:"claude",label:"Anthropic · Claude Opus 5.5",kind:"chat",provider:"anthropic",model:process.env.CLAUDE_CHAT_MODEL||"claude-opus-5-5"},
{id:"luna",label:"Fard021 · Luna",kind:"chat",provider:"openai",model:process.env.OPENAI_TEXT_MODEL||"gpt-6-luna"},
{id:"sol",label:"Fard021 · Sol",kind:"chat",provider:"openai",model:process.env.OPENAI_REASONING_MODEL||"gpt-6.1-sol"},
{id:"astra",label:"Fard021 · Astra",kind:"chat",provider:"openai",model:process.env.OPENAI_PRO_MODEL||"gpt-6-astra"},
{id:"image",label:"Fard021 · تصویر",kind:"image",provider:"openai",model:process.env.OPENAI_IMAGE_MODEL||"gpt-image-2"},
{id:"video",label:"Fard021 · ویدیو",kind:"video",provider:"openai",model:process.env.OPENAI_VIDEO_MODEL||"sora-2"},
{id:"realtime",label:"Fard021 · مکالمه زنده",kind:"voice",provider:"openai",model:process.env.OPENAI_VOICE_MODEL||"gpt-realtime"},
{id:"transcribe",label:"Fard021 · گفتار به متن",kind:"transcribe",provider:"openai",model:process.env.OPENAI_TRANSCRIBE_MODEL||"gpt-4o-mini-transcribe"},
{id:"tts",label:"Fard021 · متن به گفتار",kind:"tts",provider:"openai",model:process.env.OPENAI_TTS_MODEL||"gpt-4o-mini-tts"},
{id:"compat",label:"Provider سازگار با OpenAI",kind:"chat",provider:"compat",model:process.env.COMPAT_CHAT_MODEL||""},
{id:"music-webhook",label:"موسیقی · Provider خارجی",kind:"music",provider:"webhook",model:process.env.MUSIC_WEBHOOK_MODEL||""},
{id:"image-webhook",label:"تصویر · Provider خارجی",kind:"image",provider:"webhook",model:process.env.IMAGE_WEBHOOK_MODEL||""},
{id:"video-webhook",label:"ویدیو · Provider خارجی",kind:"video",provider:"webhook",model:process.env.VIDEO_WEBHOOK_MODEL||""}];
export const models=()=>[...registry,...freeModels()].filter(x=>x.provider!=="openai"||!!process.env.OPENAI_API_KEY).filter(x=>x.provider!=="compat"||!!compat).filter(x=>x.provider!=="xai"||!!xai).filter(x=>x.provider!=="heretic"||!!heretic).filter(x=>x.provider!=="anthropic"||!!claudeKey).filter(x=>x.provider!=="google"||!!process.env.GEMINI_API_KEY).filter(x=>x.provider!=="webhook"||!!process.env[`${x.kind.toUpperCase()}_WEBHOOK_URL`]);
const clientFor=provider=>provider==="compat"?compat:provider==="xai"?xai:openai;
function requireClient(provider="openai"){const c=clientFor(provider);if(!c)throw new Error(`کلید Provider ${provider} روی سرور تنظیم نشده است.`);return c}
async function claudeChat(messages){
  if(!claudeKey)throw new Error("ANTHROPIC_API_KEY روی Render تنظیم نشده است.");
  const system=chatSystem();
  const body={model:process.env.CLAUDE_CHAT_MODEL||"claude-opus-5-5",max_tokens:Number(process.env.CLAUDE_MAX_TOKENS||4096),system,messages:messages.map(m=>({role:m.role==="assistant"?"assistant":"user",content:String(m.content||"")}))};
  const r=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"content-type":"application/json","x-api-key":claudeKey,"anthropic-version":"2023-06-01"},body:JSON.stringify(body)});
  const d=await r.json().catch(()=>({}));
  if(!r.ok)throw new Error(d.error?.message||"Claude API خطا داد");
  return {text:d.content?.filter(x=>x.type==="text").map(x=>x.text).join("")||"",model:d.model||body.model,provider:"anthropic"};
}
export async function moderate(input){if(!openai)return {flagged:false};const r=await openai.moderations.create({model:"omni-moderation-latest",input});return r.results?.[0]||{flagged:false}}
function buildInput(messages,fileIds=[]){const out=messages.map(x=>({role:x.role,content:x.content}));if(fileIds?.length&&out.length){const last=out[out.length-1];last.content=[{type:"input_text",text:String(last.content)},...fileIds.map(id=>({type:"input_file",file_id:id}))]}return out}
export async function chat({messages,modelId="luna",fileIds=[],webSearch=false}){
if(modelId==="gemini-free")return geminiChat({messages,webSearch});
if(modelId==="hf-free")return hfChat({messages});
if(modelId==="heretic"){if(!heretic)throw new Error("HERETIC_BASE_URL روی Render تنظیم نشده است.");const model=process.env.HERETIC_CHAT_MODEL||"p-e-w/Qwen3-4B-Instruct-2507-heretic-v4";const r=await heretic.chat.completions.create({model,messages:messages.map(x=>({role:x.role,content:String(x.content||"")})),max_tokens:Number(process.env.HERETIC_MAX_TOKENS||4096),temperature:Number(process.env.HERETIC_TEMPERATURE||0.7)});return {text:r.choices?.[0]?.message?.content||"",model:r.model||model,provider:"heretic",id:r.id}}
if(modelId==="claude")return claudeChat(messages);
if(modelId==="grok"){
  if(!xai)throw new Error("XAI_API_KEY روی Render تنظیم نشده است.");
  const r=await xai.responses.create({model:process.env.XAI_CHAT_MODEL||"grok-4.7",instructions:chatSystem(),input:buildInput(messages,fileIds)});
  return {text:r.output_text||"",model:process.env.XAI_CHAT_MODEL||"grok-4.7",provider:"xai",id:r.id};
}
if(!process.env.OPENAI_API_KEY&&process.env.GEMINI_API_KEY)return geminiChat({messages,webSearch});
if(modelId==="pollinations-text"){const c=new OpenAI({apiKey:process.env.POLLINATIONS_API_KEY,baseURL:"https://gen.pollinations.ai/v1"});const r=await c.chat.completions.create({model:process.env.POLLINATIONS_TEXT_MODEL||"openai",messages});return {text:r.choices?.[0]?.message?.content||"",model:r.model||process.env.POLLINATIONS_TEXT_MODEL||"openai",provider:"pollinations"}}
const m=registry.find(x=>x.id===modelId&&x.kind==="chat")||registry.find(x=>x.kind==="chat")||registry[0],c=requireClient(m.provider),mod=await moderate(messages.map(x=>x.content).join("\n"));if(mod.flagged)throw new Error("این درخواست با سیاست‌های ایمنی سرویس سازگار نیست.");
const params={model:m.model,instructions:process.env.ASSISTANT_SYSTEM_PROMPT||"تو دستیار فارسی Fard021 AI هستی. دقیق، صمیمی، مفید و شفاف پاسخ بده.",input:buildInput(messages,fileIds)};if(webSearch&&m.provider==="openai")params.tools=[{type:"web_search"}];const r=await c.responses.create(params);return {text:r.output_text||"",model:m.model,provider:m.provider,id:r.id}}
export async function streamChat({messages,modelId="luna",fileIds=[],webSearch=false,onEvent}){if(["gemini-free","hf-free","heretic","pollinations-text","grok","claude"].includes(modelId)){const r=await chat({messages,modelId,fileIds,webSearch});onEvent?.({type:"delta",text:r.text});onEvent?.({type:"done",text:r.text});return r}const m=registry.find(x=>x.id===modelId&&x.kind==="chat")||registry.find(x=>x.kind==="chat")||registry[0],c=requireClient(m.provider),params={model:m.model,instructions:process.env.ASSISTANT_SYSTEM_PROMPT||"تو دستیار فارسی Fard021 AI هستی. دقیق، صمیمی، مفید و شفاف پاسخ بده.",input:buildInput(messages,fileIds),stream:true};if(webSearch&&m.provider==="openai")params.tools=[{type:"web_search"}];const stream=await c.responses.create(params);let text="";for await(const event of stream){if(event.type==="response.output_text.delta"){text+=event.delta;onEvent?.({type:"delta",text:event.delta})}if(event.type==="response.completed")onEvent?.({type:"done",text,id:event.response?.id})}return {text,model:m.model,provider:m.provider}}
export async function uploadFile(filePath,filename){const c=requireClient();const r=await c.files.create({file:fs.createReadStream(filePath),purpose:"user_data"});return {id:r.id,filename:r.filename||filename,bytes:r.bytes}}
export async function image({prompt,modelId="nano-banana"}){if(modelId==="nano-banana"||modelId==="nano-banana-lite"){if(!process.env.GEMINI_API_KEY)throw new Error("GEMINI_API_KEY برای Nano Banana روی Render تنظیم نشده است.");const ai=new GoogleGenAI({apiKey:process.env.GEMINI_API_KEY});const model=modelId==="nano-banana-lite"?"gemini-3.1-flash-lite-image":"gemini-3.1-flash-image";const r=await ai.models.generateContent({model,contents:prompt,config:{responseModalities:["IMAGE"]}});const part=r.candidates?.[0]?.content?.parts?.find(p=>p.inlineData);if(!part?.inlineData?.data)throw new Error("Nano Banana تصویر برنگرداند.");return {dataUrl:`data:${part.inlineData.mimeType||"image/png"};base64,${part.inlineData.data}`,model,provider:"google"}}if(modelId==="pollinations-image"||!process.env.OPENAI_API_KEY)return pollinationsImage({prompt});const m=registry.find(x=>x.id===modelId)||registry.find(x=>x.kind==="image");if(m.provider==="webhook")return webhook(m.kind,prompt);const c=requireClient(m.provider);if((await moderate(prompt)).flagged)throw new Error("پرامپت تصویر مجاز نیست.");const r=await c.images.generate({model:m.model,prompt,size:process.env.OPENAI_IMAGE_SIZE||"1024x1024"}),b64=r.data?.[0]?.b64_json;if(!b64)throw new Error("تصویر از سرویس دریافت نشد.");return {dataUrl:`data:image/png;base64,${b64}`,model:m.model,provider:m.provider}}
export async function createVideo({prompt,seconds="8",size="1280x720",modelId="veo-google"}){const m=registry.find(x=>x.id===modelId)||registry.find(x=>x.kind==="video");if(m.provider==="webhook")return webhook(m.kind,prompt,{seconds,size});if(m.provider==="google"){if(!process.env.GEMINI_API_KEY)throw new Error("GEMINI_API_KEY برای Veo روی Render تنظیم نشده است.");if((await moderate(prompt)).flagged)throw new Error("پرامپت ویدیو مجاز نیست.");const ai=new GoogleGenAI({apiKey:process.env.GEMINI_API_KEY});const aspectRatio=String(size).includes("x1280")?"9:16":"16:9";const operation=await ai.models.generateVideos({model:m.model,prompt,config:{durationSeconds:8,aspectRatio}});return {id:operation.name,status:operation.done?"completed":"queued",provider:"google",model:m.model,operationName:operation.name};}requireClient(m.provider);if((await moderate(prompt)).flagged)throw new Error("پرامپت ویدیو مجاز نیست.");const r=await fetch("https://api.openai.com/v1/videos",{method:"POST",headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:m.model,prompt,seconds,size})}),d=await r.json();if(!r.ok)throw new Error(d.error?.message||"ساخت ویدیو ناموفق بود");return d}
export async function getVideo(id,provider="openai",model="video"){if(provider==="google"){if(!process.env.GEMINI_API_KEY)throw new Error("GEMINI_API_KEY تنظیم نشده است.");const ai=new GoogleGenAI({apiKey:process.env.GEMINI_API_KEY});const operation=await ai.operations.getVideosOperation({operation:{name:id}});if(operation.done){const v=operation.response?.generatedVideos?.[0]?.video;return {status:"completed",progress:100,videoUri:v?.uri||null};}return {status:"processing",progress:0};}requireClient();const r=await fetch(`https://api.openai.com/v1/videos/${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`}}),d=await r.json();if(!r.ok)throw new Error(d.error?.message||"خطا در وضعیت ویدیو");return d}
export async function downloadVideo(id,provider="openai",model="video"){if(provider==="google"){if(!process.env.GEMINI_API_KEY)throw new Error("GEMINI_API_KEY تنظیم نشده است.");const ai=new GoogleGenAI({apiKey:process.env.GEMINI_API_KEY});const operation=await ai.operations.getVideosOperation({operation:{name:id}});if(!operation.done)throw new Error("ویدیو هنوز آماده نیست.");const video=operation.response?.generatedVideos?.[0]?.video;if(!video)throw new Error("فایل ویدیو پیدا نشد.");const out=os.tmpdir()+"/fard021-"+Date.now()+".mp4";await ai.files.download({file:video,downloadPath:out});const buf=fs.readFileSync(out);try{fs.unlinkSync(out)}catch{}return buf;}requireClient();const r=await fetch(`https://api.openai.com/v1/videos/${encodeURIComponent(id)}/content`,{headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`}});if(!r.ok)throw new Error("دانلود ویدیو ناموفق بود");return Buffer.from(await r.arrayBuffer())}
export async function transcribe(file){const c=requireClient(),r=await c.audio.transcriptions.create({file:fs.createReadStream(file),model:process.env.OPENAI_TRANSCRIBE_MODEL||"gpt-4o-mini-transcribe",language:"fa"});return {text:r.text||""}}
export async function music({prompt}){return webhook("music",prompt)}
export async function speech({text,voice="marin"}){if(process.env.GEMINI_API_KEY&&process.env.FREE_MODE_ONLY==="true")return geminiTTS({text,voice:process.env.GEMINI_TTS_VOICE||"Kore"});const c=requireClient(),r=await c.audio.speech.create({model:process.env.OPENAI_TTS_MODEL||"gpt-4o-mini-tts",voice,input:text,response_format:"mp3"});return Buffer.from(await r.arrayBuffer())}
export async function realtimeCall(sdp,{instructions,model}={}){requireClient();const session={type:"realtime",model:model||process.env.OPENAI_VOICE_MODEL||"gpt-realtime",audio:{output:{voice:process.env.OPENAI_REALTIME_VOICE||"marin"}},instructions:instructions||process.env.ASSISTANT_SYSTEM_PROMPT||"تو دستیار فارسی Fard021 AI هستی."};const form=new FormData();form.append("sdp",sdp,{contentType:"application/sdp"});form.append("session",JSON.stringify(session),{contentType:"application/json"});const r=await fetch("https://api.openai.com/v1/realtime/calls",{method:"POST",headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`},body:form});const text=await r.text();if(!r.ok)throw new Error(text||"ساخت نشست صوتی ناموفق بود");return {sdp:text}}
async function webhook(kind,prompt,extra={}){const url=process.env[`${kind.toUpperCase()}_WEBHOOK_URL`];if(!url)throw new Error(`Provider ${kind} پیکربندی نشده است.`);const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json",...(process.env.MEDIA_WEBHOOK_TOKEN?{Authorization:`Bearer ${process.env.MEDIA_WEBHOOK_TOKEN}`}: {})},body:JSON.stringify({prompt,...extra})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Provider ${kind} خطا داد`);return d}