const GEMINI_BASE='https://generativelanguage.googleapis.com/v1beta/models';
const HF_BASE='https://router.huggingface.co/v1';
export const freeCatalog=[
{id:'gemini-free',name:'Gemini · Free Tier',provider:'Google Gemini',kind:'chat',model:process.env.GEMINI_MODEL||'gemini-2.5-flash-lite',requiresKey:true,freeTier:true,note:'سهمیه رایگان API؛ محدودیت‌ها متغیرند.'},
{id:'hf-free',name:'Hugging Face · Free Credits',provider:'Hugging Face',kind:'chat',model:process.env.HF_CHAT_MODEL||'Qwen/Qwen3-4B-Instruct-2507',requiresKey:true,freeTier:true,note:'اعتبار رایگان محدود؛ پس از آن پولی است.'},
{id:'pollinations-image',name:'Pollinations · Image',provider:'Pollinations',kind:'image',model:process.env.POLLINATIONS_IMAGE_MODEL||'flux',requiresKey:true,freeTier:false,note:'به حساب/کلید Pollinations و اعتبار آن وابسته است.'},
{id:'pollinations-text',name:'Pollinations · Text',provider:'Pollinations',kind:'chat',model:process.env.POLLINATIONS_TEXT_MODEL||'openai',requiresKey:true,freeTier:false,note:'Provider چندمدلی؛ شرایط مصرف/اعتبار متغیر است.'}];
export function freeModels(){return freeCatalog.filter(x=>x.provider==='Google Gemini'?!!process.env.GEMINI_API_KEY:x.provider==='Hugging Face'?!!process.env.HF_TOKEN:x.provider==='Pollinations'?!!process.env.POLLINATIONS_API_KEY:true)}
function geminiMessages(messages){return messages.map(m=>({role:m.role==='assistant'?'model':'user',parts:[{text:String(m.content||'')}] }))}
export async function geminiChat({messages,webSearch=false}){if(!process.env.GEMINI_API_KEY)throw new Error('GEMINI_API_KEY تنظیم نشده است.');const model=process.env.GEMINI_MODEL||'gemini-2.5-flash-lite';const body={systemInstruction:{parts:[{text:process.env.ASSISTANT_SYSTEM_PROMPT||'تو دستیار فارسی Fard021 AI هستی. دقیق، صمیمی، مفید و شفاف پاسخ بده.'}]},contents:geminiMessages(messages),generationConfig:{temperature:.7}};if(webSearch)body.tools=[{googleSearch:{}}];const r=await fetch(`${GEMINI_BASE}/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(process.env.GEMINI_API_KEY)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error?.message||'Gemini خطا داد');const text=(d.candidates||[]).flatMap(c=>c.content?.parts||[]).map(p=>p.text||'').join('');if(!text)throw new Error('Gemini پاسخ متنی برنگرداند.');return {text,model,provider:'gemini'}}
export async function hfChat({messages}){if(!process.env.HF_TOKEN)throw new Error('HF_TOKEN تنظیم نشده است.');const model=process.env.HF_CHAT_MODEL||'Qwen/Qwen3-4B-Instruct-2507';const r=await fetch(`${HF_BASE}/chat/completions`,{method:'POST',headers:{Authorization:`Bearer ${process.env.HF_TOKEN}`,'Content-Type':'application/json'},body:JSON.stringify({model,messages:messages.map(x=>({role:x.role,content:String(x.content||'')})),max_tokens:1200,temperature:.7})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error?.message||'Hugging Face خطا داد');const text=d.choices?.[0]?.message?.content||'';if(!text)throw new Error('Hugging Face پاسخ متنی برنگرداند.');return {text,model,provider:'huggingface'}}
export async function pollinationsImage({prompt}){if(!process.env.POLLINATIONS_API_KEY)throw new Error('POLLINATIONS_API_KEY تنظیم نشده است.');const model=process.env.POLLINATIONS_IMAGE_MODEL||'flux';const url=`https://gen.pollinations.ai/image/${encodeURIComponent(prompt)}?model=${encodeURIComponent(model)}&width=1024&height=1024`;const r=await fetch(url,{headers:{Authorization:`Bearer ${process.env.POLLINATIONS_API_KEY}`}});if(!r.ok)throw new Error(`Pollinations تصویر: HTTP ${r.status}`);const buf=Buffer.from(await r.arrayBuffer());return {dataUrl:`data:${r.headers.get('content-type')||'image/jpeg'};base64,${buf.toString('base64')}`,model,provider:'pollinations'}}
export async function geminiTTS({text,voice='Kore'}){if(!process.env.GEMINI_API_KEY)throw new Error('GEMINI_API_KEY تنظیم نشده است.');const model=process.env.GEMINI_TTS_MODEL||'gemini-2.5-flash-preview-tts';const body={contents:[{role:'user',parts:[{text:String(text)}]}],generationConfig:{responseModalities:['AUDIO'],speechConfig:{voiceConfig:{voice}}};const r=await fetch(`${GEMINI_BASE}/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':process.env.GEMINI_API_KEY},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error?.message||'Gemini TTS خطا داد');const b64=d.candidates?.[0]?.content?.parts?.find(p=>p.inlineData)?.inlineData?.data;if(!b64)throw new Error('Gemini TTS صوتی برنگرداند.');return Buffer.from(b64,'base64')}